### ISSUE TITLE
Mocking methods called by constructor

### ISSUE THREAD

**Issue by garethellis36** [phake/phake#221]
I'm trying to make a partial mock of a class but I'm getting stung by something that is happening when the original constructor is run. Disabling the original constructor by not providing any constructor arguments to `Phake::partialMock()` is not an option for this use case.

Example:

``` php
<?php
class Foo
{
    public function __construct()
    {
        $this->doSomethingAnnoying();
    }

    protected function doSomethingAnnoying()
    {
        //do something annoying here
    }
}
```

I'd be very happy to be told that this is in fact possible, but as far as I can see there is no way to stub the method `Foo::doSomethingAnnoying()` with `Phake::partialMock()` because by the time you get to the `Phake::when()` call, the original method has already been called by the constructor.

**Comment by mlively** [comment]
Sorry, for the late answer, but better late than never?

You can actually accomplish this just using Phake::mock() and passing in new Phake_Stubber_Answers_ParentDelegate() as the second parameter. The second parameter to mock() allows you to override the default answer so all stubs will now invoke the parent method as opposed to just returning null.

Phake::partialMock() just provides a shortcut option for Phake::mock() that does two specific things. First it changes the default answer for stubs from null (or smart answer for type hinted code) to calling the parent (as seen above) and it calls the original constructor. Really its primary use is to test abstract classes where you want to exercise the class but can't directly instantiate the class because of the abstract methods.

In your case where you are wanting to put legacy code under test, it is probably better to use Phake::mock() and either stub methods that need to be invoked using Phake::when($mock)->method->thenCallParent() or if that is the majority of methods, passing the second parameter as shown above.
