### ISSUE TITLE
Impossible to stub __construct?

### ISSUE THREAD

**Issue by niconoe-** [phake/phake#298]
Hi there.

I'm using either Phake 3.1 or Phake 4.0 depending on the projetcs I'm working on. Tests are always run with PHPUnit 9.5.
In both case, I encounter a situation where I can't find a way to stub one of the `__construct` call I have to do in my code, making my test irrelevant in some parts and this raise now mutants I can't kill when using PHP Infection.

I managed to reduce and obfuscate my snippets to concentrate on what seems to me the buggy issue:

Class to test:
```php
class RealClass
{
    public function __construct(array $params)
    {
        //Do stuff with params that we don't care
    }

    public function doStuff()
    {
        // Do stuff that we don't care.
    }
}
```

Test class:
```php
class RealClassTest
{
    public function testTest(): void
    {
        $phake = Phake::mock(RealClass::class);
        $phake->doStuff();
        Phake::verify($phake)->__call('doStuff', []); // This one is OK
        $phake->__construct(['this', 'is', 1, 'param']);
        Phake::verify($phake)->__call('__construct', [['this', 'is', 1, 'param']]); // This one is not.
    }
}
```

In english words, I need to test that I managed to call the `__construct` method of my object while it's actually not done with a `new` keyword (because my object was already instanced and I just want to rewrite it, not building a new one). But this fails, probably because of the very specific magic `__construct` behavior.
Just like the `__call` has a special procedure to be tested, is there anything similar with `__constrcut` that I can use?

Thanks a lot

**Comment by adoy** [comment]
Hi,

The code generated in the `__construct` method of the Mock is not recording any call to it since it's the *constructor* of the object and it doesn't really make sense to check that the *constructor* was called by your test.

It's true that `__construct` is special in the way that it could be called again when the object is already instanciated. I really think that even if it's possible it's really a bad thing to do, since the purpose of this method is to *construct* the object and not to be called a second time. If you do really want to initialize your object you should do something like

```
class Foo
{
    public function __construct(array $params = [])
    { 
        $this->initialise($params);
    } 

    public function initialise(array $params = [])
    { 
        // your logic
    }
}
```

Do you think this would be a valid solution in your case ? If not, it would be nice to have more details on your actual use case so that we can judge if it would make sense to record subsequent calls to the `__construct` method so that thet can be verified.

Thanks for using Phake and opening this issue.

**Comment by niconoe-** [comment]
Thank you very much for your answer.

Unfortunately, the `__construct` method I'm using is the one from `Doctrine\DBAL\Connection` (see https://github.com/doctrine/dbal/blob/3.1.x/src/Connection.php#L167) and I can't overwrite this.

To give you more details about what's behind there: it's a private bundle that manage a multitenancy business structure splitted by databases (each customer have its own database). To explain briefly, we need to connect to a private internal database to fetch the customer identifiers and database names, so we instanciate a connection first. Once the identifiers are fetched, we close the internal connection and re-open it but with the customer's identifiers so we're now connected to its database.

That's why we need this really bad thing in order to not create a new instance but just reuse the previous one (also some parameters aren't change between the swap and we don't want to transfer them from previous object to new one, we only want to "adapt" the previous object to the new one).

If this is not possible do to the special case of the `__construct`, I'll try to find another way to avoid that bad call, but this would mean doing some risky changes I can't afford right now :smiley: .

Maybe now with more detailed information you know a solution or something?

And it's always a pleasure to use Phake: we are using it in my company for more than 2 years now and we manage to do a lot thanks to this awesome project! So thanks to you to provide and maintain such a thing!

**Comment by adoy** [comment]
Thanks for the details. To be honest this is really a tricky/hackish case and I don't think modifying Phake to handle this kind of use case is a good idea.

If you don't have any other option, (I would not recommand to do that normaly) but could it help you to have something like :
```php
class Connection extends Doctrine\DBA\Connection
{
    public function reinit(array $params)
    {
        $this->__construct($params);
    }
}
```
You'll have the ability to call `reinit` instead of `__construct` to make it work. It will be testable and just a little bit less confusing in the code instead of seeing something like `$config->__construct()`

**Comment by niconoe-** [comment]
I completely understand that introducing this edge case into Phake could be too difficult and too risky, especially when looking at my particular use case which is uncommon.

I came with a similar solution on first thought but I find it not really elegant.
I have the ability to delay my QA work about this specific case I can’t handle right now as I have other projects to take care too, and I also need to refactor this project in PHP 8, so maybe I will be able to find something more suitable to finally kill all of my mutants ;).

In the meantime, I saw no evidence of the impossibility to achieve to stub the `__construct` method in the Phake documentation. Could it be possible to add something about that so other lost souls like me could at least understand there is currently no way to stub the direct call to the constructor?

Thanks a lot for your help and to taking time to search solutions I could use.
