### ISSUE TITLE
Interfaces with a method called "list" cannot be mocked

### ISSUE THREAD

**Issue by beberlei** [phake/phake#299]
It seems `list` being also a keyword leads Phake to not generate a mock method and throw an error:

```
Fatal error: Class ObservationEvents_PHAKE00c1f2189c5b601 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (....\Model\ObservationEvents::list) invendor/phake/phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code on line 2
```

This is for Phake 3.1.8

**Comment by adoy** [comment]
Hi Benjamin !

Thanks for the bug report. Phake 3.1.8 (and older versions) do have a list of reserved keywords. This was introduced in 
https://github.com/phake/phake/issues/57 

I think this was more an issue with the gearman extension that should not use reserved keywords as method name. 
Furthermore with PHP7+ context sensitive lexer, the current list in place is not valid anymore since a lot of those keywords (all but `__halt_compiler` can now be used as valid method name.

I already removed this reserved Keywords list in Phake 4.0.0 but i'm going to also remove it in 3.8 since it support PHP >= 7.

**Comment by adoy** [comment]
Done.

3.1.9 is released with this bugfix. Thanks for the report.

**Comment by beberlei** [comment]
@adoy oh thanks, i would have happily updated to 4.0 as well :) thank you

**Comment by adoy** [comment]
You're welcome :-). It is of course also recommanded to upgrade to Phake 4.0 with PHP7.1+ support (including 8.0). Basic Phake usage is pretty much compatible with 3.1.8 version.
